-- Colunas para I-485 Part 1. Information About You
ALTER TABLE public.i485_applications
  ADD COLUMN IF NOT EXISTS p1_first_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_middle_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_last_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_date_of_birth DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_sex TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_city_of_birth TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_country_of_birth TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_country_of_citizenship TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_alien_number TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_passport_number TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_i94_number TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS p1_current_status TEXT DEFAULT NULL;
